/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bittu_jni_BittuplayerJNI */

#ifndef _Included_bittu_jni_BittuplayerJNI
#define _Included_bittu_jni_BittuplayerJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef bittu_jni_BittuplayerJNI_NO_ERROR
#define bittu_jni_BittuplayerJNI_NO_ERROR 0L
#undef bittu_jni_BittuplayerJNI_STREAM_EOF
#define bittu_jni_BittuplayerJNI_STREAM_EOF -1L
#undef bittu_jni_BittuplayerJNI_NO_AUDIO_STREAMS
#define bittu_jni_BittuplayerJNI_NO_AUDIO_STREAMS -2L
#undef bittu_jni_BittuplayerJNI_NETWORK_ERROR
#define bittu_jni_BittuplayerJNI_NETWORK_ERROR -3L
#undef bittu_jni_BittuplayerJNI_DEMUXING_ERROR
#define bittu_jni_BittuplayerJNI_DEMUXING_ERROR -4L
#undef bittu_jni_BittuplayerJNI_DECODING_ERROR
#define bittu_jni_BittuplayerJNI_DECODING_ERROR -5L
#undef bittu_jni_BittuplayerJNI_SEEKING_ERROR
#define bittu_jni_BittuplayerJNI_SEEKING_ERROR -6L
#undef bittu_jni_BittuplayerJNI_INTERNAL_ERROR
#define bittu_jni_BittuplayerJNI_INTERNAL_ERROR -7L
#undef bittu_jni_BittuplayerJNI_RESAMPLER_ERROR
#define bittu_jni_BittuplayerJNI_RESAMPLER_ERROR -8L
#undef bittu_jni_BittuplayerJNI_OPUS_ERROR
#define bittu_jni_BittuplayerJNI_OPUS_ERROR -9L
#undef bittu_jni_BittuplayerJNI_MEMORY_ERROR
#define bittu_jni_BittuplayerJNI_MEMORY_ERROR -10L
/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    stream
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bittu_jni_BittuplayerJNI_stream
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    getErrorState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bittu_jni_BittuplayerJNI_getErrorState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    getErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bittu_jni_BittuplayerJNI_getErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    isStreamOpened
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bittu_jni_BittuplayerJNI_isStreamOpened
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    getDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bittu_jni_BittuplayerJNI_getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bittu_jni_BittuplayerJNI_getPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bittu_jni_BittuplayerJNI_pause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    unpause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bittu_jni_BittuplayerJNI_unpause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    isSeekable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_bittu_jni_BittuplayerJNI_isSeekable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bittu_jni_BittuplayerJNI_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    read
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bittu_jni_BittuplayerJNI_read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    readFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bittu_jni_BittuplayerJNI_readFinalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bittu_jni_BittuplayerJNI
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bittu_jni_BittuplayerJNI_finalize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
